# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27cd616650b4f51ff1b3768afbc2f9c63b58190f1308e4ca6d6ee8a603e2a18984e794910a307741db4ebdf8fda78f44fd7e9fec493886c78f12b41c283ef5de
  db_user: root
  db_password: fouesnant

test:
  secret_key_base: 46a67ba8c8ba40139a12ed5f9381d3c1d96fa89b4f77d78e7011712a225f7db92561220ce758bdfbbc5811597ca78fd91c327203383d0cc83390d90329de3427

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
